### ISSUE TITLE
App doesn't work with iOS 12.2 (iPhone 7)

### ISSUE THREAD

**Issue by davesen83** [clawoo/gexporter-ios#1]
[DEBUG] Did open IPv4 listening socket 3
[DEBUG] Did open IPv6 listening socket 4
[INFO] GCDWebServer started on port 22222 and reachable at http://192.168.0.36:22222/
2019-04-13 22:47:27.351944+0200 gexporter[324:9822] Presenting view controllers on detached view controllers is discouraged <gexporter.FileListViewController: 0x159e0c3a0>.
2019-04-13 22:47:27.899786+0200 gexporter[324:9822] Unbalanced calls to begin/end appearance transitions for <UINavigationController: 0x15a015c00>.
[DEBUG] Did enter background
[DEBUG] Did close IPv6 listening socket 4
[DEBUG] Did close IPv4 listening socket 3
[INFO] GCDWebServer stopped
2019-04-13 22:47:36.515579+0200 gexporter[324:9822] Could not load IOSurface for time string. Rendering locally instead.
[DEBUG] Will enter foreground
[DEBUG] Did open IPv4 listening socket 3
[DEBUG] Did open IPv6 listening socket 4
[INFO] GCDWebServer started on port 22222 and reachable at http://192.168.0.36:22222/
[DEBUG] Did open connection on socket 5
[DEBUG] Did connect
[DEBUG] Did start background task
[DEBUG] Connection received 264 bytes on socket 5
[WARNING] Ignoring 'Content-Type' header for 'GET' request on "/dir.json?short=1&longname=1&type=FIT -- http://localhost:22222/"
[DEBUG] Connection on socket 5 preflighting request "GET /dir.json" with 264 bytes body
[DEBUG] Connection on socket 5 processing request "GET /dir.json" with 264 bytes body
[DEBUG] Connection sent 156 bytes on socket 5
[DEBUG] Connection sent 21 bytes on socket 5
[DEBUG] Did close connection on socket 5
[VERBOSE] [::1:22222] ::1:49677 404 "GET /dir.json" (264 | 177)
[DEBUG] Did disconnect
[DEBUG] Did end background task
[DEBUG] Did open connection on socket 5
[DEBUG] Did connect
[DEBUG] Did start background task
[DEBUG] Connection received 264 bytes on socket 5
[WARNING] Ignoring 'Content-Type' header for 'GET' request on "/dir.json?short=1&longname=1&type=FIT -- http://localhost:22222/"
[DEBUG] Connection on socket 5 preflighting request "GET /dir.json" with 264 bytes body
[DEBUG] Connection on socket 5 processing request "GET /dir.json" with 264 bytes body
[DEBUG] Connection sent 156 bytes on socket 5
[DEBUG] Connection sent 21 bytes on socket 5
[DEBUG] Did close connection on socket 5
[VERBOSE] [::1:22222] ::1:49678 404 "GET /dir.json" (264 | 177)
[DEBUG] Did disconnect
[DEBUG] Did end background task
[DEBUG] Did open connection on socket 5
[DEBUG] Did connect
[DEBUG] Did start background task
[DEBUG] Connection received 264 bytes on socket 5
[WARNING] Ignoring 'Content-Type' header for 'GET' request on "/dir.json?short=1&longname=1&type=FIT -- http://localhost:22222/"
[DEBUG] Connection on socket 5 preflighting request "GET /dir.json" with 264 bytes body
[DEBUG] Connection on socket 5 processing request "GET /dir.json" with 264 bytes body
[DEBUG] Connection sent 156 bytes on socket 5
[DEBUG] Connection sent 21 bytes on socket 5
[DEBUG] Did close connection on socket 5
[VERBOSE] [::1:22222] ::1:49679 404 "GET /dir.json" (264 | 177)
[DEBUG] Did disconnect
[DEBUG] Did end background task
[DEBUG] Did open connection on socket 5
[DEBUG] Did connect
[DEBUG] Did start background task
[DEBUG] Connection received 264 bytes on socket 5
[WARNING] Ignoring 'Content-Type' header for 'GET' request on "/dir.json?short=1&longname=1&type=FIT -- http://localhost:22222/"
[DEBUG] Connection on socket 5 preflighting request "GET /dir.json" with 264 bytes body
[DEBUG] Connection on socket 5 processing request "GET /dir.json" with 264 bytes body
[DEBUG] Connection sent 156 bytes on socket 5
[DEBUG] Connection sent 21 bytes on socket 5
[DEBUG] Did close connection on socket 5
[VERBOSE] [::1:22222] ::1:49680 404 "GET /dir.json" (264 | 177)
[DEBUG] Did disconnect
[DEBUG] Did end background task
[DEBUG] Did enter background
[DEBUG] Did close IPv6 listening socket 4
[DEBUG] Did close IPv4 listening socket 3
[INFO] GCDWebServer stopped
[DEBUG] Will enter foreground
[DEBUG] Did open IPv4 listening socket 3
[DEBUG] Did open IPv6 listening socket 4
[INFO] GCDWebServer started on port 22222 and reachable at http://192.168.0.36:22222/
2019-04-13 22:48:02.686766+0200 gexporter[324:9822] [CoreBluetooth] API MISUSE: <CBCentralManager: 0x283d7dcc0> has no restore identifier but the delegate implements the centralManager:willRestoreState: method. Restoring will not be supported
2019-04-13 22:48:02.689266+0200 gexporter[324:9822] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil'
*** First throw call stack:
(0x2330ac518 0x2322879f8 0x233025f8c 0x232fa1520 0x104e74894 0x104e85900 0x104a104f8 0x104a0ff08 0x104a133ac 0x104ef3c14 0x104a101a8 0x1049fff24 0x104a0c284 0x104a0c960 0x25f5f9270 0x25f5f8be4 0x25f6052f0 0x25eeb2b34 0x25eeb09c4 0x25eeb068c 0x25eeb51cc 0x25eeb5fb0 0x25eeb5084 0x25eeb9d84 0x25f1e93b8 0x235a27920 0x1059a0c74 0x1059a4840 0x235a610bc 0x235a60d58 0x235a61310 0x23303e2bc 0x23303e23c 0x23303db24 0x233038a60 0x233038354 0x23523879c 0x25f5efb68 0x104a0d5bc 0x232afe8e0)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by alinradut** [comment]
I can't tell where this crash is occurring. Can you run the app while attached to Xcode with crash breakpoints enabled and let me know where it's crashing?

**Comment by davesen83** [comment]
Hi

I analyzed a bit more and the problem is, when there are more than one device in connect app, and your app gets the list of devices (the list seems to be correct), it crashes. If there is only one device in connect app, it works.
I will do this for you today evening @ home. I don‘t really know xcode very good.
Now I have the next problem, that when I want to get the track list on my watch with gimporter, than the first request for fit files will be responsed correctly but than there will be a 404 response. And then there will be no gpx request afterwards from gimporter.
I changed the code, so that the fit request handles gpx files and then I got the list in gimporter, could also download track with „download complete“ message, but there is no track on my watch.

Thank you very much for your help.
Regards Dave

PS: I updated to web server V3.5.2 and CocoaPods V1.7.1 beta

**Comment by davesen83** [comment]
Hello

when I ran the with Xcode it will crash in AppDelegate.swift:





I think, the problem occurs here:



My url is:

url	URL	"gexporter://device-select-resp?ciqApp=Connect&ciqBundle=com.garmin.connect.mobile&ciqScheme&ciqSdkVersion=10000&d0ID=6E9AC8DB-AB21-CE02-20BA-BD52D39CD20C&d0Model=fenix%205X%20Plus&d0Name=fenix%205X%20Plus&d1ID&d1Model=Oregon%20700&d1Name=Oregon%20700"	

You see, there is a Fenix 5x plus and an Oregon 700.



When I step over from this line onDevicesChanged?(), it crashes.

Can you help me?

Regards
Dave

**Comment by davesen83** [comment]
Hello again

when I delete the Oregon 700 in connect app, it works until I want to get the track list with gimporter.

Then I got these responses from web server:

DEBUG] Did open connection on socket 5
[DEBUG] Did connect
[DEBUG] Did start background task
[DEBUG] Connection received 264 bytes on socket 5
[WARNING] Ignoring 'Content-Type' header for 'GET' request on "/dir.json?short=1&longname=1&type=FIT -- http://localhost:22222/"
[DEBUG] Connection on socket 5 preflighting request "GET /dir.json" with 264 bytes body
[DEBUG] Connection on socket 5 processing request "GET /dir.json" with 264 bytes body
[DEBUG] Connection sent 156 bytes on socket 5
[DEBUG] Connection sent 21 bytes on socket 5
[DEBUG] Did close connection on socket 5
[VERBOSE] [::1:22222] ::1:56849 404 "GET /dir.json" (264 | 177)
[DEBUG] Did disconnect
[DEBUG] Did end background task

Do you have an idea, why your web server response 404?

Regards
Dave
________________________________________

mail: davesen@gmail.com
mobile: +41 78 649 83 55

**Comment by alinradut** [comment]
Okay, so two issues seem to be at play here, one is the device parsing and the other is the webserver returning 404.

I'll address them separately, the device parsing first.

Your Oregon 700 cannot be identified by the ConnectIQ SDK as it's being parsed in DevicesManager.swift:31:
```
po devices
▿ 2 elements
  - 0 : <IQDevice: 0x1908480, uuid = 6E9AC8DB-AB21-CE02-20BA-BD52D39CD20C, modelName = "fenix 5X Plus", friendlyName = "fenix 5X Plus">
  - 1 : <IQDevice: 0x190a500, uuid = (null), modelName = "Oregon 700", friendlyName = "Oregon 700">
```

There is no UUID for it. When it's being passed back into the Connect IQ SDK via devicesManager.connectIq.register in DevicesViewController.swift:17 the SDK crashes as it probably uses the UUID as the key. 

Unfortunately there is not much anyone can do about it, bar from filtering out devices which do not have an UUID. I checked and there's no new ConnectIQ SDK for iOS, so we're stuck with 1.3 for the moment.

The fix is modifying the code in DevicesManager like this:
```
        devices = connectIq.parseDeviceSelectionResponse(from: url)?.compactMap({ $0 as? IQDevice }).filter({ $0.uuid != nil }) ?? []
```
Will commit this change soon.

**Comment by alinradut** [comment]
Okay so I've analyzed the 404 issue. gexporter will return a 404 whenever there are no files to be returned for the given "type", so when the FIT files are requested, there are none to be found so a 404 is returned. 

I have no idea why gimporter does not ask for GPX files, but in your case, you can comment out the `switch` in `handleListing` and replace it with `files = storage.gpxFiles`.

**Comment by davesen83** [comment]
> Okay, so two issues seem to be at play here, one is the device parsing and the other is the webserver returning 404.
> 
> I'll address them separately, the device parsing first.
> 
> Your Oregon 700 cannot be identified by the ConnectIQ SDK as it's being parsed in DevicesManager.swift:31:
> 
> ```
> po devices
> ▿ 2 elements
>   - 0 : <IQDevice: 0x1908480, uuid = 6E9AC8DB-AB21-CE02-20BA-BD52D39CD20C, modelName = "fenix 5X Plus", friendlyName = "fenix 5X Plus">
>   - 1 : <IQDevice: 0x190a500, uuid = (null), modelName = "Oregon 700", friendlyName = "Oregon 700">
> ```
> There is no UUID for it. When it's being passed back into the Connect IQ SDK via devicesManager.connectIq.register in DevicesViewController.swift:17 the SDK crashes as it probably uses the UUID as the key.
> 
> Unfortunately there is not much anyone can do about it, bar from filtering out devices which do not have an UUID. I checked and there's no new ConnectIQ SDK for iOS, so we're stuck with 1.3 for the moment.
> 
> The fix is modifying the code in DevicesManager like this:
> 
> ```
>         devices = connectIq.parseDeviceSelectionResponse(from: url)?.compactMap({ $0 as? IQDevice }).filter({ $0.uuid != nil }) ?? []
> ```
> Will commit this change soon.

Hello

ok now it works also with Oregon 700 connected in Garmin Connect app. And I have to wait for a new SDK, which also support Oregon right?

I modified your code, so that fit request also handles gpx files. That works obviously. Download can be started with gimporter, "Download complete" message appears, but track is not in my track list afterwards. Do you have an idea?

**Comment by davesen83** [comment]
> Okay so I've analyzed the 404 issue. gexporter will return a 404 whenever there are no files to be returned for the given "type", so when the FIT files are requested, there are none to be found so a 404 is returned.
> 
> I have no idea why gimporter does not ask for GPX files, but in your case, you can comment out the `switch` in `handleListing` and replace it with `files = storage.gpxFiles`.

Where do you know how to answer for requests from gimporter? Is this documented? Maybe 404 is an response for gimporter which results in an "connection failed" (this is displayed) and no other requests are executed.

**Comment by alinradut** [comment]
The `/dir.json` request is handled from `WebServer.swift:31` which calls `handleListing(request)`. If there are no files to be returned, a 404 is returned from `WebServer.swift:89`.
