### ISSUE TITLE
Export larger GPX files

### ISSUE THREAD

**Issue by patricks** [clawoo/gexporter-ios#2]
Hi,  I tried to use this tool to upload my geocaching gpx files. But I am only able to upload really small gpx files. I have tried a gpx files with 1,2mb didn’t work. Is this normal or should this work? I am using a gpsmap 66 gpsr

**Comment by alinradut** [comment]
There is no limitation from the iOS side, this sounds more like a gimporter/gps device issue, the iOS app will serve the GPX file as is.

**Comment by patricks** [comment]
Yes, I think you are right, I think BLE is still too slow, but there is a new IQ Connect release (3.1 Beta) which also supports WLAN syncing, maybe this will fix this problem.
